spring:
  datasource:
    url: jdbc:mysql://yqingyu.top:3306/crm
    username: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: yyj.981010
  mvc:
    view:
      suffix: .jsp
      prefix: /pages/


server:
  port: 8888
  servlet:
    context-path: /crm


mybatis:
  type-aliases-package: com.qy.pojo
#  mapper-locations: classpath:com/qy/mapper/*.xml

mapper:
  mappers:
    - com.qy.mapper.UserMapper
    - com.qy.mapper.ProductMapper
  notEmpty: true

pagehelper:
  auto-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
  page-size-zero: true
